INSERT INTO CUISINE(typeID, description) VALUES (6, "Afghani")
INSERT INTO CUISINE(typeID, description) VALUES (152, "African")
INSERT INTO CUISINE(typeID, description) VALUES (1, "American")
INSERT INTO CUISINE(typeID, description) VALUES (4, "Arabian")
INSERT INTO CUISINE(typeID, description) VALUES (3, "Asian")
INSERT INTO CUISINE(typeID, description) VALUES (401, "Asian Fusion")
INSERT INTO CUISINE(typeID, description) VALUES (193, "BBQ")
INSERT INTO CUISINE(typeID, description) VALUES (5, "Bakery")
INSERT INTO CUISINE(typeID, description) VALUES (227, "Bar Food")
INSERT INTO CUISINE(typeID, description) VALUES (270, "Beverages")
INSERT INTO CUISINE(typeID, description) VALUES (182, "Breakfast")
INSERT INTO CUISINE(typeID, description) VALUES (133, "British")
INSERT INTO CUISINE(typeID, description) VALUES (247, "Bubble Tea")
INSERT INTO CUISINE(typeID, description) VALUES (168, "Burger")
INSERT INTO CUISINE(typeID, description) VALUES (22, "Burmese")
INSERT INTO CUISINE(typeID, description) VALUES (30, "Cafe")
INSERT INTO CUISINE(typeID, description) VALUES (491, "Cajun")
INSERT INTO CUISINE(typeID, description) VALUES (381, "Canadian")
INSERT INTO CUISINE(typeID, description) VALUES (121, "Cantonese")
INSERT INTO CUISINE(typeID, description) VALUES (158, "Caribbean")
INSERT INTO CUISINE(typeID, description) VALUES (25, "Chinese")
INSERT INTO CUISINE(typeID, description) VALUES (161, "Coffee and Tea")
INSERT INTO CUISINE(typeID, description) VALUES (153, "Cuban")
INSERT INTO CUISINE(typeID, description) VALUES (192, "Deli")
INSERT INTO CUISINE(typeID, description) VALUES (100, "Desserts")
INSERT INTO CUISINE(typeID, description) VALUES (411, "Dim Sum")
INSERT INTO CUISINE(typeID, description) VALUES (541, "Diner")
INSERT INTO CUISINE(typeID, description) VALUES (959, "Donuts")
INSERT INTO CUISINE(typeID, description) VALUES (268, "Drinks Only")
INSERT INTO CUISINE(typeID, description) VALUES (651, "Eastern European")
INSERT INTO CUISINE(typeID, description) VALUES (149, "Ethiopian")
INSERT INTO CUISINE(typeID, description) VALUES (38, "European")
INSERT INTO CUISINE(typeID, description) VALUES (40, "Fast Food")
INSERT INTO CUISINE(typeID, description) VALUES (112, "Filipino")
INSERT INTO CUISINE(typeID, description) VALUES (298, "Fish and Chips")
INSERT INTO CUISINE(typeID, description) VALUES (45, "French")
INSERT INTO CUISINE(typeID, description) VALUES (501, "Frozen Yogurt")
INSERT INTO CUISINE(typeID, description) VALUES (274, "Fusion")
INSERT INTO CUISINE(typeID, description) VALUES (134, "German")
INSERT INTO CUISINE(typeID, description) VALUES (156, "Greek")
INSERT INTO CUISINE(typeID, description) VALUES (181, "Grill")
INSERT INTO CUISINE(typeID, description) VALUES (143, "Healthy Food")
INSERT INTO CUISINE(typeID, description) VALUES (791, "Hong Kong Style")
INSERT INTO CUISINE(typeID, description) VALUES (233, "Ice Cream")
INSERT INTO CUISINE(typeID, description) VALUES (148, "Indian")
INSERT INTO CUISINE(typeID, description) VALUES (154, "International")
INSERT INTO CUISINE(typeID, description) VALUES (140, "Iranian")
INSERT INTO CUISINE(typeID, description) VALUES (135, "Irish")
INSERT INTO CUISINE(typeID, description) VALUES (55, "Italian")
INSERT INTO CUISINE(typeID, description) VALUES (207, "Jamaican")
INSERT INTO CUISINE(typeID, description) VALUES (60, "Japanese")
INSERT INTO CUISINE(typeID, description) VALUES (164, "Juices")
INSERT INTO CUISINE(typeID, description) VALUES (178, "Kebab")
INSERT INTO CUISINE(typeID, description) VALUES (67, "Korean")
INSERT INTO CUISINE(typeID, description) VALUES (136, "Latin American")
INSERT INTO CUISINE(typeID, description) VALUES (66, "Lebanese")
INSERT INTO CUISINE(typeID, description) VALUES (69, "Malaysian")
INSERT INTO CUISINE(typeID, description) VALUES (70, "Mediterranean")
INSERT INTO CUISINE(typeID, description) VALUES (73, "Mexican")
INSERT INTO CUISINE(typeID, description) VALUES (137, "Middle Eastern")
INSERT INTO CUISINE(typeID, description) VALUES (147, "Moroccan")
INSERT INTO CUISINE(typeID, description) VALUES (50, "North Indian")
INSERT INTO CUISINE(typeID, description) VALUES (861, "Northern Chinese")
INSERT INTO CUISINE(typeID, description) VALUES (110, "Others")
INSERT INTO CUISINE(typeID, description) VALUES (139, "Pakistani")
INSERT INTO CUISINE(typeID, description) VALUES (183, "Patisserie")
INSERT INTO CUISINE(typeID, description) VALUES (162, "Peruvian")
INSERT INTO CUISINE(typeID, description) VALUES (82, "Pizza")
INSERT INTO CUISINE(typeID, description) VALUES (219, "Polish")
INSERT INTO CUISINE(typeID, description) VALUES (87, "Portuguese")
INSERT INTO CUISINE(typeID, description) VALUES (983, "Pub Food")
INSERT INTO CUISINE(typeID, description) VALUES (511, "Quebecois")
INSERT INTO CUISINE(typeID, description) VALUES (320, "Ramen")
INSERT INTO CUISINE(typeID, description) VALUES (84, "Russian")
INSERT INTO CUISINE(typeID, description) VALUES (998, "Salad")
INSERT INTO CUISINE(typeID, description) VALUES (601, "Salvadorean")
INSERT INTO CUISINE(typeID, description) VALUES (304, "Sandwich")
INSERT INTO CUISINE(typeID, description) VALUES (210, "Scottish")
INSERT INTO CUISINE(typeID, description) VALUES (83, "Seafood")
INSERT INTO CUISINE(typeID, description) VALUES (128, "Sichuan")
INSERT INTO CUISINE(typeID, description) VALUES (611, "Somali")
INSERT INTO CUISINE(typeID, description) VALUES (85, "South Indian")
INSERT INTO CUISINE(typeID, description) VALUES (471, "Southern")
INSERT INTO CUISINE(typeID, description) VALUES (89, "Spanish")
INSERT INTO CUISINE(typeID, description) VALUES (86, "Sri Lankan")
INSERT INTO CUISINE(typeID, description) VALUES (141, "Steak")
INSERT INTO CUISINE(typeID, description) VALUES (177, "Sushi")
INSERT INTO CUISINE(typeID, description) VALUES (211, "Swedish")
INSERT INTO CUISINE(typeID, description) VALUES (212, "Syrian")
INSERT INTO CUISINE(typeID, description) VALUES (190, "Taiwanese")
INSERT INTO CUISINE(typeID, description) VALUES (179, "Tapas")
INSERT INTO CUISINE(typeID, description) VALUES (163, "Tea")
INSERT INTO CUISINE(typeID, description) VALUES (964, "Teriyaki")
INSERT INTO CUISINE(typeID, description) VALUES (150, "Tex-Mex")
INSERT INTO CUISINE(typeID, description) VALUES (95, "Thai")
INSERT INTO CUISINE(typeID, description) VALUES (142, "Turkish")
INSERT INTO CUISINE(typeID, description) VALUES (451, "Ukrainian")
INSERT INTO CUISINE(typeID, description) VALUES (308, "Vegetarian")
INSERT INTO CUISINE(typeID, description) VALUES (99, "Vietnamese")
