INSERT INTO CUISINE(typeID, description) VALUES (1, 'American');
INSERT INTO CUISINE(typeID, description) VALUES (4, 'Arabian');
INSERT INTO CUISINE(typeID, description) VALUES (3, 'Asian');
INSERT INTO CUISINE(typeID, description) VALUES (401, 'Asian Fusion');
INSERT INTO CUISINE(typeID, description) VALUES (193, 'BBQ');
INSERT INTO CUISINE(typeID, description) VALUES (5, 'Bakery');
INSERT INTO CUISINE(typeID, description) VALUES (227, 'Bar Food');
INSERT INTO CUISINE(typeID, description) VALUES (270, 'Beverages');
INSERT INTO CUISINE(typeID, description) VALUES (133, 'British');
INSERT INTO CUISINE(typeID, description) VALUES (247, 'Bubble Tea');
INSERT INTO CUISINE(typeID, description) VALUES (168, 'Burger');
INSERT INTO CUISINE(typeID, description) VALUES (30, 'Cafe');
