INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (32751974,'1981-7-28',3,2,3,2,'Pretty average burger restaurant. The burger and fries were tasty, but nothing special. The ambiance and staff were pleasant, but not partic...',16665661);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (31584549,'2018-6-2',2,1,1,0,'First off, I've never seen a menu with more spelling mistakes in my life, from the Angus beef parry to whatever a poituine is. Probably spot...',16665661);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (31001412,'1983-11-26',5,3,1,0,'Had the chicken wrap with garden salad. Delicious food and great service. Have had burger and pouting in the past, also very good. Reasonabl...',16665661);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (30766393,'1981-11-5',3,0,2,1,'Its a very cute place, but veryy very greasy. Buns itself has so much oil. I could feel my chin pores opening. Its not really busy in there ...',16665661);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (29896636,'2011-12-3',1,1,0,0,'Quite honestly I was not impressed at all with my experience here. The food was okay however both mine and my boyfriend's order got messed u...',16665661);

INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (32703493,'2008-9-7',3,0,1,0,'This is definitely one of the best looking diners in Ottawa. The decor is iconic 60s style and very fun. It's also open 24 hours which makes...',16663281);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (31297984,'2017-4-9',3,3,3,0,'I've been to Zak's a few times, and it's just ok. Nothing extraordinary about the place. A good place to chill with friends and get breakfas...',16663281);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (31296957,'2002-3-15',1,0,1,0,'Went to Zak's in the Byward Market for lunch. We ordered milkshakes which were really good, yet I am allergic to whip cream and cream becaus...',16663281);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (30794591,'2008-7-23',3,2,1,0,'Classic greasy spoon spot.  After a night out there isn't anything like their curly fries poutine or their cheese and chilli foot long dogs....',16663281);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (29322793,'1985-5-7',5,0,5,4,'I've gone to Zak's Diner several times now and I've yet to be disappointed. The food is just perfect and don't get me started on their milks...',16663281);

INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (31847855,'2006-7-25',4,4,4,1,'Prince Gourmet is a very good Lebanese Place, everything is homemade in Ottawa. They only serve the freshest ingredients and the service is ...',16666124);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (28702528,'2012-10-22',1,1,0,0,'Ordered lunch with prince gourmet and after over an hour of waiting called skip the dishes to see where my food was.. was told the restauran...',16666124);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (28609072,'1993-3-7',1,1,0,1,'I have been here a few times. The last time I went the cook making the shawarma had just got back from a smoking break. Didn't wash his hand...',16666124);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (24376362,'2002-4-5',1,0,0,1,'Have been there a few times and was displeased with the chicken shawarma. They either made it too try, or too wet with too much sauce. The g...',16666124);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (13863976,'1985-12-14',0,0,0,0,'Excellent Family Platter!. I stop and get the family platter on a regular basis and it is always good. Tons of rice, potatos, salad, chicken...',16666124);

INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (33308388,'1983-4-23',5,0,0,5,'What a gem! Every plate we saw, on our table and other tables, looked so delicious. Best service possible, friendly, fast, and efficient. Ve...',16664001);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (31668498,'1986-12-3',5,0,5,2,'We love this place!!! Food is consistently delicious and despite how busy it gets, the service is generally fast and efficient. The seafood/...',16664001);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (29834887,'1984-5-18',4,4,4,1,'First time eating Korean food.  Small place, quick friendly service.  Very good had beef stir fry.  Definately return.  Reasonable price and...',16664001);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (29664806,'1981-7-1',3,0,0,1,'This is a good place for authentic Korean dishes. I thought it was great and business is booming, considering it was full the whole time. Th...',16664001);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (28559662,'1994-11-8',3,2,1,3,'Small hidden gem in Ottawa. Little house style restaurant in downtown Ottawa. We ordered a pork bone soup (Gamjatang) each which was delicio...',16664001);

INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (33165110,'2003-3-18',3,1,3,1,'The food was decent. Some things were very tasty, others weren't that great.   Atmosphere is great, but the service left something to be de...',18535306);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (32216324,'1996-3-23',5,4,3,0,'Waitress helping us was absolutely perfect. She gave everyone at the table 2 different taste tests of wine. And was very educated on the men...',18535306);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (31362322,'1981-3-25',4,3,2,3,'I love the atmosphere of this restaurant, the decor and seating arrangement are beautiful. The food is amazing, my go to is the Tandoori chi...',18535306);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (31249741,'2003-2-24',1,1,1,0,'Hated my experience, way too much staff, way too many people serving me and my steak was extremely overcooked. The manager didn't care that ...',18535306);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (30986307,'1999-3-2',4,2,4,2,'Went here for drinks the other night shortly after it opened. It's a better atmosphere and looks more esthetically pleasing on the inside th...',18535306);

INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (29343706,'1980-11-2',5,0,0,1,'I'm was struggling to find good restaurants on UberEATS until I found Gladstone. I've ordered from there several times now and I've tried th...',16665516);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (28052506,'2012-10-27',4,0,4,2,'Did Uber eats. Someone called immediately to say they ran out of wings (I ordered very late). She offered roasted Chicken in its place and i...',16665516);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (26148678,'2007-1-10',4,0,3,1,'What a pleasant little surprise this place was. The Haitian rice was decadent and cooked in a rich shrimp broth. The plantain were tasty and...',16665516);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (24290165,'1993-11-22',4,2,3,0,'Delicious BBQ chicken. The extra sauce on the side of the poutine is very spicy! Tried the BBQ chicken poutine and a half chicken combo. Als...',16665516);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (23683066,'2016-6-21',0,0,0,0,'Yes!. This place is wonderful. Delicious chicken and sides, charming staff and a fun atmosphere. It felt like a vacation. The ginger/hibiscu...',16665516);

INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (32301295,'2003-4-17',2,0,2,0,'For a quick takeout it works. I'm not impressed with their bagels but many people are. Kettleman's is usually very busy at any time of day a...',16663453);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (32248471,'2013-7-19',4,3,1,4,'Came here last week on my way home to pick up a half dozen bagels. I was in the mood for sesame, specifically, but decided to also try their...',16663453);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (31258055,'1985-12-8',4,2,1,4,'A far as Montreal bagels go, this place is tops in Ottawa. Open 24/7, 365 this place never closes. They only accept cash, which is good to k...',16663453);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (31237836,'1984-8-19',5,3,0,4,'I always come here for bagels. Last time I got a dozen bagels and when I took them home I realized that they had something green on them and...',16663453);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (28740972,'1987-1-11',1,0,0,0,'disgusting service! i've asked for bagel with butter and jam and told specifically that i do not wanna peanut butter, I want just regular on...',16663453);

INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (28403499,'2007-10-6',5,0,4,0,'My go- to bakery for birthday cakes, squares and moist, delicious cupcakes. From chocolate to lemon and everything in between, I have never ...',16664780);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (13865458,'1996-4-7',0,0,0,0,'Cupcakes made very well. I am a huge fan of cupcakes, and the cupcakes made here are pretty good. the cake was moist and soft and the icing ...',16664780);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (13865455,'1988-6-28',0,0,0,0,'Dissapointing to say the least. Upon returning to the Glebe for a weekend trip after years of being away from the city, I stumbled upon what...',16664780);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (13865452,'1983-3-27',0,0,0,0,'Great baked goods and treats. we are regulars. We are especially fans of the tasty challahs made only on Fridays.',16664780);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (13865449,'2000-3-17',0,0,0,0,'Relatively new place but they put out an amazing product. Great croissants and the chocolate ones are so decadant. Lots of local traffic whi...',16664780);

INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (13879201,'1989-3-19',0,0,0,0,'Customer service does need a huge boost. This is not the first i was ignored when standing by the cashier to order only to serve the person ...',16665150);

INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (30003924,'2004-3-20',3,2,3,2,'Large, spacious venue that's great for hosting social events. Tried appetizers here and they were quite good - above the standard of regular...',16665913);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (29073826,'1984-3-23',1,0,1,1,'We were a bit hesitant going to Lowertown after looking up the menu and not seeing a terribly broad selection - but we went because we had a...',16665913);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (27055687,'1992-5-15',2,0,1,2,'Good food, good beer selection, and excellent wait staff. Just don't go in on Thursdays. They have this retarded as shat that thinks he's a ...',16665913);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (26776178,'1995-1-19',4,2,3,3,'Wonderful service. Very cool atmosphere. You can see right into the kitchen and see the beer being brewed on site. We stopped in for snacks ...',16665913);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (26195903,'2006-7-8',4,1,2,0,'Solid venue, tasty home brewed beer selection. The lager was a highlight. I really enjoyed the pork belly sandwich, just the perfect texture...',16665913);

INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (30465955,'1992-6-22',3,0,3,1,'Large, spacious pub, great venue for large groups. The selection of beer and drinks is quite impressive - I'm not a big beer fan, but they d...',16663239);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (28239451,'1990-7-22',4,2,1,3,'My husband and I went here for dinner. Enjoyed our dinners, I had the chicken Pot Pie and my husband had the Shepards Pie. Food was tasty an...',16663239);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (28067494,'1999-5-14',2,2,2,1,'My wife and I went in early Saturday evening for dinner. The food was excellent but our server ruined our evening.   Sir John A's is our GO...',16663239);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (27928183,'1992-8-4',3,3,3,3,'I honestly wish I could rate higher but the food quality wasn't quite there. The service was friendly, welcoming and efficient. The selectio...',16663239);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (25568183,'1996-5-5',3,3,0,2,'This place has a great selection of draught beer.  Tons of local micro-brews.  Food was quite good as well.  The usual pub fare, but done we...',16663239);

INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (31835030,'1985-11-26',3,2,3,2,'The location is really nice and I love the rooftop patio. But I found the food ultimately disappointing. I got a smoothie that was pretty fl...',17840846);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (31743563,'2008-4-10',4,4,4,3,'Yummy fresh food, friendly staff, and great selection of fresh juices & smoothies. Pure Kitchen is health conscious but perhaps they should ...',17840846);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (29936482,'1982-6-11',4,2,2,0,'Clean place, great service, delicious smoothies, and surprisingly tasty snacks. Popped by in the afternoon for a small bite and was pleasant...',17840846);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (29690702,'2016-5-19',1,1,1,1,'If there was a way to give a zero, I would. The pretentiousness of this place is matched by the overpriced food, which tastes like nothing. ...',17840846);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (29438986,'2016-9-10',5,0,3,3,'Some of the best food I've ever had and I'm a carnivore. I've yet to try anything there that didn't satisfy.  - Large portion sizes - Compl...',17840846);

INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (33849860,'1988-7-8',5,2,1,1,'Been there twice.   Fantastic fish.    Brought both kids with me and they loved it too.   Fish was perfectly battered and quantity is substa...',16663285);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (30266882,'1993-7-9',3,1,2,1,'I have eaten at the Glen many times. I have found the deep fried haddock with the lite batter to be the best choice. Almost on every occasio...',16663285);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (29747277,'2014-1-8',4,4,1,1,'The Glen has been around for over two decades now, so, as always in the restaurant world, it must be doing something right. On a typical Sat...',16663285);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (26624707,'2012-4-9',4,0,1,3,'Service was friendly. The Western dip was nothing special. I ordered the Modern Shepherds Pie - it was delicious! Love the gravy! My one com...',16663285);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (24266907,'1992-2-3',5,4,3,3,'Amazing experience, as per usual! The Glen has just launched a new menu.... They still have all my faves, brought back some of the old favou...',16663285);

INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (25280420,'2005-9-17',4,1,3,3,'Convenient, modern little spot perfect for a mid-shopping break or a way to cool down in the hot summer months. Bubblicity has been a staple...',16664417);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (23683171,'1986-4-4',0,0,0,0,'Not good.. I have been twice: both were disappointing. The most recent had no flavor and was too watery. They charge extra for the "bubble" ...',16664417);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (13853032,'2011-4-21',0,0,0,0,'Worst bubble tea and dumplings EVER. I've tried so many bubble teas and dumplings, but im wondring how this restaurant could still exist. Ha...',16664417);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (13853029,'1982-6-23',4,2,3,3,'Mmmm... coconut sherbet... Do want.. Excellent, super tasty bubble teas and sherbets, at decent prices. The large sizes are HUGE and probabl...',16664417);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (13853026,'2013-2-8',0,0,0,0,'Sooooooo slow. Takes way too long',16664417);

INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (33704076,'2002-7-2',4,4,0,3,'Love their cornbread, chicken, and mac n cheese. Their red meat isn't amazing, but it's still good and tastes great with their excellent sau...',16664699);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (31145676,'1996-3-12',4,0,4,3,'This restaurant was shown on the tv show 'You Gotta Eat Here' and we (9 in total) went based on a suggestion from a person we were travellin...',16664699);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (31138276,'1998-12-1',4,4,4,4,'Stopped by for dinner and the food was delicious. I really enjoyed the "smoqued" corn bread and the macaroni and cheese was super good. High...',16664699);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (30886405,'2011-1-28',2,1,0,0,'There's just way too much hype for this place being featured on "You Gotta Eat Here." The restaurant wasn't fully packed for an early late l...',16664699);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (30873334,'1994-12-22',2,0,1,1,'Went here for diner with my girlfriend. She had the spinach salad with steak. Steak was very chewy. I had the picnic plater. A bit overprice...',16664699);

INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (33378547,'2013-12-1',3,3,3,3,'Great cupcakes! I bought a cupcake from here once and it was great! Nothing extravagant but it was good overall. It’s a very small place s...',16664621);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (32152531,'1996-7-5',3,2,2,0,'I have mixed feelings on this place. I really like the idea, but I'm just never wowed enough by their treats. The cupcakes are good, but not...',16664621);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (30765776,'1992-10-27',4,4,2,3,'I'm addicted. The vanilla ,vanilla cupcakes invade my dreams. The icing is perfect, and cupcakes are always fresh. Friendly and helpful staf...',16664621);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (29781996,'1983-9-20',3,2,2,0,'The store is very pleasing visually, super cute. Service was alright. Polite but not super friendly, generally didn't speak much. I got the ...',16664621);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (28390708,'1987-11-8',4,3,1,4,'Amazing cupcake selection! Cupcake was delicious, white got chocolate on the other hand I would not recommend. Great place to sit for a whil...',16664621);

INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (25100113,'2000-12-2',4,0,1,4,'Came here for an almond milk chai latte, and it was just as delicious as I've come to expect from bridgehead. Staff were friendly, and servi...',16663237);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (24302112,'1998-7-4',4,3,4,4,'For great coffee, a relaxed atmosphere and great snacks I would recommend bridgehead. The staff are nice but don't go out of their way to he...',16663237);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (23683011,'1983-4-1',0,0,0,0,'Bridgehead on Elgin Street. Hi Coffee lovers:  I have to admit that I really enjoy my coffee in the morning. Bridgehead has been growing l...',16663237);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (23414689,'1990-2-8',0,0,0,0,'Lose the attitude!. I just moved to Ottawa and went to Bridgehead for the first time. I found the staff to be unfriendly and the barista had...',16663237);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (13794697,'2000-8-23',0,0,0,0,'Bridgehead. It's my favourite place to go for a very nice atmosphere and really seriously good coffee. i'm happy they have so many locations...',16663237);

INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (33564639,'1992-7-27',1,0,0,0,'For the extremely high rating on Zomato, the food was disappointing. My friend and I ordered the brie phyllo pastry starter that barely had ...',16663252);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (33517168,'1993-11-6',3,1,1,0,'I visited this restaurant on recommendations from and almost insistence from a family member. She said if you want a good burger you have to...',16663252);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (32557124,'1995-5-10',3,0,0,0,'Large work affair. Burgers are astounding, albeit a tad greasy. Great burger fixings. Chicken breasts were hard and not tender with adequate...',16663252);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (31250121,'2008-10-24',5,3,5,1,'Awesome Chez Lucien burger and chicken burger. Both with the best fries we have best fries we have had in a while. Friendly, welcoming staff...',16663252);
INSERT INTO RATING(UserID, varDate, Price, Food, Mood, Staff, Comments, RestaurantID) VALUES (31200319,'1989-11-12',3,2,2,0,'A very busy day for Chez Lucien as "La Machine" was roaming through the market. Service was understandably slow. My chicken sandwich was acc...',16663252);

